apiVersion: v1
kind: ConfigMap
metadata: {name: app-config, namespace: devops-lab}
data:
  APP_VERSION: v0.1.0
  POSTGRES_HOST: postgres
  POSTGRES_DB: lab
  POSTGRES_USER: lab
  REDIS_HOST: redis
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: api, namespace: devops-lab}
spec:
  replicas: 2
  strategy: {type: RollingUpdate, rollingUpdate: {maxUnavailable: 0, maxSurge: 1}}
  selector: {matchLabels: {app: api}}
  template:
    metadata: {labels: {app: api}}
    spec:
      containers:
        - name: api
          image: control.lab:5000/devops-lab-api:v0.1.0
          imagePullPolicy: IfNotPresent
          envFrom: [{configMapRef: {name: app-config}}]
          env:
            - name: POSTGRES_PASSWORD
              valueFrom: {secretKeyRef: {name: app-secrets, key: POSTGRES_PASSWORD}}
          ports: [{name: http, containerPort: 5000}]
          livenessProbe: {httpGet: {path: /health, port: http}, initialDelaySeconds: 10, periodSeconds: 10}
          readinessProbe: {httpGet: {path: /ready, port: http}, initialDelaySeconds: 5, periodSeconds: 5}
          resources: {requests: {cpu: 100m, memory: 128Mi}, limits: {cpu: 500m, memory: 512Mi}}
          securityContext: {allowPrivilegeEscalation: false, runAsNonRoot: true, capabilities: {drop: [ALL]}}
---
apiVersion: v1
kind: Service
metadata: {name: api, namespace: devops-lab}
spec: {selector: {app: api}, ports: [{name: http, port: 80, targetPort: http}]}

